version: "3.9"

networks:
    postgres-network:
        driver: bridge

services:
    web:
        build:
            context: .
            dockerfile: .\web.Dockerfile
        image: web-django
        container_name: web-container
        environment:
            - DB_NAME=django_db
            - DB_USER=postgres
            - DB_PASS=postgresdb
            - DB_HOST=db-container
            - DB_PORT=5432
        command: sh -c "python3 /projeto/wait_for_it.py && python3 /projeto/manage.py makemigrations && python3 /projeto/manage.py migrate && python3 /projeto/manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        networks:
            - postgres-network
        depends_on:
            - "db"
            - "db_admin"
        volumes:
            - .\projeto:/projeto
    db_admin:
        image: dpage/pgadmin4
        container_name: db-admin-container
        environment:
            - PGADMIN_DEFAULT_EMAIL=math.artero@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=pgadmin
        ports:
            - "15432:80"
        networks:
            - postgres-network
        depends_on:
            - "db"
    db:
        build:
            context: .
            dockerfile: .\db.Dockerfile
        image: db-postgres
        container_name: db-container
        environment:
            - POSTGRES_PASSWORD=postgresdb
        ports:
            - "5432:5432"
        networks:
            - postgres-network
        volumes:
            - .\volume-db:/var/lib/postgresql/data